nginx:
  # image: nginx:latest
  build: ./nginx
  container_name: nginx-container
  ports: 
    - 80:80
  links:
    - php
  volumes-from: 
    - app-data
    
php:
  image: php:7.2-fpm
  container_name: php-container
  expose:
    - 9000
  volumes-from: 
    - app-data

app-data:
  image: php:7.2-fpm
  container_name: app-data-container
  volumes: 
    - ./www/html/:/var/www/html/
  command: "true"
